# Generated by Django 6.0.4 on 2026-04-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product_pics/default.png', null=True, upload_to='product_pics/'),
        ),
    ]
