# Generated by Django 6.0.5 on 2026-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=256, verbose_name='Descrição')),
                ('cor', models.CharField(max_length=256, verbose_name='Cor')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('preco', models.FloatField(verbose_name='Preço')),
            ],
        ),
    ]
