# Generated by Django 6.0.4 on 2026-07-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='aniversario',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='alterado_em',
            new_name='changed_in',
        ),
        migrations.RenameField(
            model_name='usermodel',
            old_name='criado_em',
            new_name='created_in',
        ),
    ]
