# Generated by Django 6.0.4 on 2026-07-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_aniversario_usermodel_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='perfil',
            new_name='profile',
        ),
    ]
