# Generated by Django 6.1 on 2026-08-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_produto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='msgPromocao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
