# Generated by Django 6.1 on 2026-09-19 22:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_carrinho_carrinhoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='produtos_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
